version: "3"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=raspberrypi_metrics
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin123
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  telegraf:
    image: telegraf:1.14
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  influxdb-data:
  grafana-data:
